const ships = [
  [
    {
      open: false,
      selected: false,
      x: 0,
      y: 0,
      ship: {
        imagePath: 'submarino',
        kind: 'submarino',
        points: 1000,
        size: 2,
        hasShip: true,
        orientacao: 'v',
      },
    },
    {
      open: false,
      selected: false,
      x: 1,
      y: 0,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 2,
      y: 0,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 3,
      y: 0,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 4,
      y: 0,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 5,
      y: 0,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 6,
      y: 0,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 7,
      y: 0,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 8,
      y: 0,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 9,
      y: 0,
      ship: {
        imagePath: 'porta-avioes',
        kind: 'portaAvioes',
        points: 300,
        size: 5,
        hasShip: true,
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 10,
      y: 0,
      ship: {
        imagePath: '',
        kind: 'portaAvioes',
        points: 300,
        size: 5,
        hasShip: true,
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 11,
      y: 0,
      ship: {
        imagePath: '',
        kind: 'portaAvioes',
        points: 300,
        size: 5,
        hasShip: true,
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 12,
      y: 0,
      ship: {
        imagePath: '',
        kind: 'portaAvioes',
        points: 300,
        size: 5,
        hasShip: true,
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 13,
      y: 0,
      ship: {
        imagePath: '',
        kind: 'portaAvioes',
        points: 300,
        size: 5,
        hasShip: true,
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 14,
      y: 0,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 15,
      y: 0,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
  ],
  [
    {
      open: false,
      selected: false,
      x: 0,
      y: 1,
      ship: {
        imagePath: '',
        kind: 'submarino',
        points: 1000,
        size: 2,
        hasShip: true,
        orientacao: 'v',
      },
    },
    {
      open: false,
      selected: false,
      x: 1,
      y: 1,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 2,
      y: 1,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 3,
      y: 1,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 4,
      y: 1,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 5,
      y: 1,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 6,
      y: 1,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 7,
      y: 1,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 8,
      y: 1,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 9,
      y: 1,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 10,
      y: 1,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 11,
      y: 1,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 12,
      y: 1,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 13,
      y: 1,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 14,
      y: 1,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 15,
      y: 1,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
  ],
  [
    {
      open: false,
      selected: false,
      x: 0,
      y: 2,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 1,
      y: 2,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 2,
      y: 2,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 3,
      y: 2,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 4,
      y: 2,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 5,
      y: 2,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 6,
      y: 2,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 7,
      y: 2,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 8,
      y: 2,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 9,
      y: 2,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 10,
      y: 2,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 11,
      y: 2,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 12,
      y: 2,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 13,
      y: 2,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 14,
      y: 2,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 15,
      y: 2,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
  ],
  [
    {
      open: false,
      selected: false,
      x: 0,
      y: 3,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 1,
      y: 3,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 2,
      y: 3,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 3,
      y: 3,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 4,
      y: 3,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 5,
      y: 3,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 6,
      y: 3,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 7,
      y: 3,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 8,
      y: 3,
      ship: {
        imagePath: 'submarino',
        kind: 'submarino',
        points: 1000,
        size: 2,
        hasShip: true,
        orientacao: 'v',
      },
    },
    {
      open: false,
      selected: false,
      x: 9,
      y: 3,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 10,
      y: 3,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 11,
      y: 3,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 12,
      y: 3,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 13,
      y: 3,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 14,
      y: 3,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 15,
      y: 3,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
  ],
  [
    {
      open: false,
      selected: false,
      x: 0,
      y: 4,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 1,
      y: 4,
      ship: {
        imagePath: 'submarino',
        kind: 'submarino',
        points: 1000,
        size: 2,
        hasShip: true,
        orientacao: 'v',
      },
    },
    {
      open: false,
      selected: false,
      x: 2,
      y: 4,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 3,
      y: 4,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 4,
      y: 4,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 5,
      y: 4,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 6,
      y: 4,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 7,
      y: 4,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 8,
      y: 4,
      ship: {
        imagePath: '',
        kind: 'submarino',
        points: 1000,
        size: 2,
        hasShip: true,
        orientacao: 'v',
      },
    },
    {
      open: false,
      selected: false,
      x: 9,
      y: 4,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 10,
      y: 4,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 11,
      y: 4,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 12,
      y: 4,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 13,
      y: 4,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 14,
      y: 4,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 15,
      y: 4,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
  ],
  [
    {
      open: false,
      selected: false,
      x: 0,
      y: 5,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 1,
      y: 5,
      ship: {
        imagePath: '',
        kind: 'submarino',
        points: 1000,
        size: 2,
        hasShip: true,
        orientacao: 'v',
      },
    },
    {
      open: false,
      selected: false,
      x: 2,
      y: 5,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 3,
      y: 5,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 4,
      y: 5,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 5,
      y: 5,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 6,
      y: 5,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 7,
      y: 5,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 8,
      y: 5,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 9,
      y: 5,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 10,
      y: 5,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 11,
      y: 5,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 12,
      y: 5,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 13,
      y: 5,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 14,
      y: 5,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 15,
      y: 5,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
  ],
  [
    {
      open: false,
      selected: false,
      x: 0,
      y: 6,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 1,
      y: 6,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 2,
      y: 6,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 3,
      y: 6,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 4,
      y: 6,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 5,
      y: 6,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 6,
      y: 6,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 7,
      y: 6,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 8,
      y: 6,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 9,
      y: 6,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 10,
      y: 6,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 11,
      y: 6,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 12,
      y: 6,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 13,
      y: 6,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 14,
      y: 6,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 15,
      y: 6,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
  ],
  [
    {
      open: false,
      selected: false,
      x: 0,
      y: 7,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 1,
      y: 7,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 2,
      y: 7,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 3,
      y: 7,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 4,
      y: 7,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 5,
      y: 7,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 6,
      y: 7,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 7,
      y: 7,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 8,
      y: 7,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 9,
      y: 7,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 10,
      y: 7,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 11,
      y: 7,
      ship: {
        imagePath: 'navio-tanque',
        kind: 'navioTanque',
        points: 750,
        size: 4,
        hasShip: true,
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 12,
      y: 7,
      ship: {
        imagePath: '',
        kind: 'navioTanque',
        points: 750,
        size: 4,
        hasShip: true,
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 13,
      y: 7,
      ship: {
        imagePath: '',
        kind: 'navioTanque',
        points: 750,
        size: 4,
        hasShip: true,
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 14,
      y: 7,
      ship: {
        imagePath: '',
        kind: 'navioTanque',
        points: 750,
        size: 4,
        hasShip: true,
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 15,
      y: 7,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
  ],
  [
    {
      open: false,
      selected: false,
      x: 0,
      y: 8,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 1,
      y: 8,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 2,
      y: 8,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 3,
      y: 8,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 4,
      y: 8,
      ship: {
        imagePath: 'contratopedeiros',
        kind: 'contratopedeiros',
        points: 500,
        size: 3,
        hasShip: true,
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 5,
      y: 8,
      ship: {
        imagePath: '',
        kind: 'contratopedeiros',
        points: 500,
        size: 3,
        hasShip: true,
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 6,
      y: 8,
      ship: {
        imagePath: '',
        kind: 'contratopedeiros',
        points: 500,
        size: 3,
        hasShip: true,
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 7,
      y: 8,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 8,
      y: 8,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 9,
      y: 8,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 10,
      y: 8,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 11,
      y: 8,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 12,
      y: 8,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 13,
      y: 8,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 14,
      y: 8,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 15,
      y: 8,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
  ],
  [
    {
      open: false,
      selected: false,
      x: 0,
      y: 9,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 1,
      y: 9,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 2,
      y: 9,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 3,
      y: 9,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 4,
      y: 9,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 5,
      y: 9,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 6,
      y: 9,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 7,
      y: 9,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 8,
      y: 9,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 9,
      y: 9,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 10,
      y: 9,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 11,
      y: 9,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 12,
      y: 9,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 13,
      y: 9,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 14,
      y: 9,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 15,
      y: 9,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
  ],
  [
    {
      open: false,
      selected: false,
      x: 0,
      y: 10,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 1,
      y: 10,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 2,
      y: 10,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 3,
      y: 10,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 4,
      y: 10,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 5,
      y: 10,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 6,
      y: 10,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 7,
      y: 10,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 8,
      y: 10,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 9,
      y: 10,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 10,
      y: 10,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 11,
      y: 10,
      ship: {
        imagePath: 'submarino',
        kind: 'submarino',
        points: 1000,
        size: 2,
        hasShip: true,
        orientacao: 'v',
      },
    },
    {
      open: false,
      selected: false,
      x: 12,
      y: 10,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 13,
      y: 10,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 14,
      y: 10,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 15,
      y: 10,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
  ],
  [
    {
      open: false,
      selected: false,
      x: 0,
      y: 11,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 1,
      y: 11,
      ship: {
        imagePath: 'contratopedeiros',
        kind: 'contratopedeiros',
        points: 500,
        size: 3,
        hasShip: true,
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 2,
      y: 11,
      ship: {
        imagePath: '',
        kind: 'contratopedeiros',
        points: 500,
        size: 3,
        hasShip: true,
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 3,
      y: 11,
      ship: {
        imagePath: '',
        kind: 'contratopedeiros',
        points: 500,
        size: 3,
        hasShip: true,
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 4,
      y: 11,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 5,
      y: 11,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 6,
      y: 11,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 7,
      y: 11,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 8,
      y: 11,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 9,
      y: 11,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 10,
      y: 11,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 11,
      y: 11,
      ship: {
        imagePath: '',
        kind: 'submarino',
        points: 1000,
        size: 2,
        hasShip: true,
        orientacao: 'v',
      },
    },
    {
      open: false,
      selected: false,
      x: 12,
      y: 11,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 13,
      y: 11,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 14,
      y: 11,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 15,
      y: 11,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
  ],
  [
    {
      open: false,
      selected: false,
      x: 0,
      y: 12,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 1,
      y: 12,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 2,
      y: 12,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 3,
      y: 12,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 4,
      y: 12,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 5,
      y: 12,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 6,
      y: 12,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 7,
      y: 12,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 8,
      y: 12,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 9,
      y: 12,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 10,
      y: 12,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 11,
      y: 12,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 12,
      y: 12,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 13,
      y: 12,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 14,
      y: 12,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 15,
      y: 12,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
  ],
  [
    {
      open: false,
      selected: false,
      x: 0,
      y: 13,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 1,
      y: 13,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 2,
      y: 13,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 3,
      y: 13,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 4,
      y: 13,
      ship: {
        imagePath: 'navio-tanque',
        kind: 'navioTanque',
        points: 750,
        size: 4,
        hasShip: true,
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 5,
      y: 13,
      ship: {
        imagePath: '',
        kind: 'navioTanque',
        points: 750,
        size: 4,
        hasShip: true,
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 6,
      y: 13,
      ship: {
        imagePath: '',
        kind: 'navioTanque',
        points: 750,
        size: 4,
        hasShip: true,
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 7,
      y: 13,
      ship: {
        imagePath: '',
        kind: 'navioTanque',
        points: 750,
        size: 4,
        hasShip: true,
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 8,
      y: 13,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 9,
      y: 13,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 10,
      y: 13,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 11,
      y: 13,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 12,
      y: 13,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 13,
      y: 13,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 14,
      y: 13,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 15,
      y: 13,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
  ],
  [
    {
      open: false,
      selected: false,
      x: 0,
      y: 14,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 1,
      y: 14,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 2,
      y: 14,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 3,
      y: 14,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 4,
      y: 14,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 5,
      y: 14,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 6,
      y: 14,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 7,
      y: 14,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 8,
      y: 14,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 9,
      y: 14,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 10,
      y: 14,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 11,
      y: 14,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 12,
      y: 14,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 13,
      y: 14,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 14,
      y: 14,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 15,
      y: 14,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
  ],
  [
    {
      open: false,
      selected: false,
      x: 0,
      y: 15,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 1,
      y: 15,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 2,
      y: 15,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 3,
      y: 15,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 4,
      y: 15,
      ship: {
        imagePath: 'contratopedeiros',
        kind: 'contratopedeiros',
        points: 500,
        size: 3,
        hasShip: true,
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 5,
      y: 15,
      ship: {
        imagePath: '',
        kind: 'contratopedeiros',
        points: 500,
        size: 3,
        hasShip: true,
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 6,
      y: 15,
      ship: {
        imagePath: '',
        kind: 'contratopedeiros',
        points: 500,
        size: 3,
        hasShip: true,
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 7,
      y: 15,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 8,
      y: 15,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 9,
      y: 15,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 10,
      y: 15,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 11,
      y: 15,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 12,
      y: 15,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 13,
      y: 15,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 14,
      y: 15,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
    {
      open: false,
      selected: false,
      x: 15,
      y: 15,
      ship: {
        hasShip: false,
        size: 0,
        kind: '',
        points: 25,
        imagePath: '',
        orientacao: 'h',
      },
    },
  ],
];
